### ISSUE TITLE
Installing scoped packages doesn't work

### ISSUE THREAD

**Issue by evil-shrike** [hayes/unpm#74]
I'm using 1.0.0 of unpm.
I published a scoped package into my registry ("@myco/package1"). It did appear in data/meta and data/tarballs folders in unpm.
Now I'm trying to install the package on a client machine but npm fails with error "fetch failed with status code 404".

**Comment by hayes** [comment]
without more detail I am not sure what do do about this.  I am going to close this for now, but If you are still having issues and want to send me some more details, I would be happy the reopen this issue.

best,
Micahel
